### ISSUE TITLE
Падение при "неудачном" вводе из потока

### ISSUE THREAD

**Issue by avasyukov** [Beloklokov101/Linal#1]
Если сделать вот так:
```
int main()
{
    Vector3D B;
    Matrix3D D;
    cin >> D >> B;
    return 0;
}
```
То внезапно будет segfault.

Хинт 1: вот прямо ровно это было в лекциях.
Хинт 2: компилятор - ваш друг, он в warning-е пытается намекнуть (возможно, для получения этого warning-а потребуется сборка с опцией ```-Wall```).

**Comment by PBeloklokov** [comment]
Понял, забыл в операторе ввода вернуть ссылку на поток.

**Comment by avasyukov** [comment]
Подтверждаю, решено
